### ISSUE TITLE
Error Rendering

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/MapDiffBot#134] opened 2021-09-25 20:31 UTC
![image](https://user-images.githubusercontent.com/85910816/134785242-7c77413a-2ef8-4b1a-b0bd-5872a10930de.png)

Octokit.ApiValidationException: Invalid request.

Only 65535 characters are allowed; 89722 were supplied.
   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 691
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 668
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 652
   at Octokit.ApiConnection.Patch[T](Uri uri, Object data, String accepts)
   at MapDiffBot.Core.GitHubManager.UpdateCheckRun(Int64 repositoryId, Int64 checkRunId, CheckRunUpdate checkRunUpdate, 
   CancellationToken cancellationToken)
   at MapDiffBot.Core.PayloadProcessor.HandleResults(PullRequest pullRequest, Int64 checkRunId, Dictionary2 diffResults, 
   IServiceScope scope, CancellationToken cancellationToken) at MapDiffBot.Core.PayloadProcessor.GenerateDiffs(PullRequest 
   pullRequest, Int64 checkRunId, IReadOnlyList1 changedDmms, IServiceScope scope, CancellationToken cancellationToken)
   at MapDiffBot.Core.PayloadProcessor.ScanPullRequestImpl(Int64 repositoryId, Int32 pullRequestNumber, IServiceScope scope, 
   CancellationToken cancellationToken)
   {"message":"Invalid request.\n\nOnly 65535 characters are allowed; 89722 were 
   supplied.","documentation_url":"https://docs.github.com/rest/reference/checks#update-a-check-run"}

**Comment by Cyberboss** [comment] 2021-09-25 20:57
Too many maps in one PR. Duplicate of #131

**Closed as completed by Cyberboss** 2021-09-25 20:57 UTC
